language: node_js

compiler: gcc
sudo: false

env:
  global:
    secure: H81E8/P/yfe9i6DKKKjAn4n2nuDO87oZbyvlWoJtMExSdUr9Q6S62/RxAOzUhsebJy9d2z4AHYcV4ZUlBflR5QsDda3nOVSF9S9ID8MGSwIisR0n/sifHZGr46aODBzuCUVsYCnVKjigtPsTl1LmgMYBthd3uroBe4IyWXPtt8VXtxZlQO/JWYJJzvGaTxMdRSpou2EUK87noVbbHhsD7zai94bbIHFW+Lvlq6x426Emdgxnw5+JpZF0K1S5y5x2PsBi87Hc0DnJm3weUPCbBN6W+PCRUjFFpIEkpc9baDBFtTlFhqawUqUcKPG3w2n2bdOCQ7LGFGRi9QarQJ5pCetu+imf0fD8hri/rSJfvPqSe14XrNjk+/V4ZUg5obXJD2nt1Nb5rMUd2Rl/06ZJsP/zzzfr1LgVjMy6gEI0y7RUtMxGErHYyUoxOW6UlYCw/fC6U4qM5NcT+Rgn9MpIEdGY+BlNuzwLYee8jTEFrQkVoKylaPpUtumEDgVi1LWnkNtoyYsAAF8cK08xKQsJ02tQ126kjM2vdNOqkdmil5aCO39IYscQXGrKnorzWMM8HKg6zAUBWFQNyLxqduZKD+vAOiBduZkEWkvajb8Zc4wNfKESI78BZ+iRqhldFHIOKhlvsj9/dwsnDd4D9jCjjje3LlbxV3utrtoyMNF13eg=

jobs:
  include:
    - stage: test
      node_js: "node"
      os: linux
      before_script: npm run lint || exit 1;
      after_success: npm run-script coverage;
    - stage: platform-test
      node_js: "node"
      os: osx
    - stage: platform-test
      node_js: "7"
      os: linux
    - stage: platform-test
      node_js: "7"
      os: osx
    - stage: platform-test
      node_js: "lts/boron"
      os: linux
    - stage: platform-test
      node_js: "lts/boron"
      os: osx
    - stage: platform-test
      node_js: "lts/argon"
      os: linux
    - stage: platform-test
      node_js: "lts/argon"
      os: osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7

before_install:
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-4.7";
      export CXX="g++-4.7";
      export LINK="gcc-4.7";
      export LINKXX="g++-4.7";
    fi
  - nvm --version
  - node --version
  - npm --version
  - gcc --version
  - g++ --version

install:
  - npm install --build-from-source

script:
  - if [ $TRAVIS_OS_NAME == "linux" ] && [ $TRAVIS_NODE_VERSION == "4" ]; then
      npm run lint || exit 1;
    fi
  - npm test

script:
  - npm test

after_success:
  - if [ $TRAVIS_OS_NAME == "linux" ] && [ $TRAVIS_NODE_VERSION == "4" ]; then
      npm run-script coverage;
    fi
  - COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
  - if [[ ${COMMIT_MESSAGE} =~ "[publish]" ]]; then $(npm bin)/node-pre-gyp package && $(npm bin)/node-pre-gyp-github publish; fi;

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules
